export interface Product {
  id: number | string;
  slug: string;
  name: { ar: string; en: string };
  description: { ar: string; en: string };
  price?: string | number;
  image_url: string;
  category_id?: number;
  category_name?: any;
  category_slug?: string;
  origin: string;
  tags?: string[];
}

export const products: Product[] = [
  // Herbs
  {
    id: 'chamomile',
    category: 'herbs',
    nameAr: 'البابونج',
    nameEn: 'Chamomile',
    descAr: 'بابونج مصري طبيعي عالي الجودة',
    descEn: 'Premium natural Egyptian chamomile',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'herbal-tea', 'natural'],
  },
  {
    id: 'peppermint',
    category: 'herbs',
    nameAr: 'النعناع البلدي',
    nameEn: 'Peppermint',
    descAr: 'نعناع مصري طازج مجفف بعناية',
    descEn: 'Fresh Egyptian peppermint, carefully dried',
    image: 'https://images.unsplash.com/photo-1628621756765-68af8c0f9395?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'mint', 'fresh'],
  },
  {
    id: 'hibiscus',
    category: 'herbs',
    nameAr: 'الكركديه',
    nameEn: 'Hibiscus',
    descAr: 'كركديه مصري بلون أحمر غني',
    descEn: 'Egyptian hibiscus with rich red color',
    image: 'https://images.unsplash.com/photo-1563891217861-7924d9c3e1c3?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'hibiscus', 'herbal-tea'],
  },
  {
    id: 'anise',
    category: 'herbs',
    nameAr: 'اليانسون',
    nameEn: 'Anise',
    descAr: 'يانسون مصري بنكهة قوية مميزة',
    descEn: 'Egyptian anise with distinctive strong flavor',
    image: 'https://images.unsplash.com/photo-1612540195400-db2fde4f3bbb?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'anise', 'spice'],
  },
  {
    id: 'marjoram',
    category: 'herbs',
    nameAr: 'البردقوش',
    nameEn: 'Marjoram',
    descAr: 'بردقوش مصري مجفف بجودة تصديرية',
    descEn: 'Dried Egyptian marjoram of export quality',
    image: 'https://images.unsplash.com/photo-1611914721853-b37b43f9d93b?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'marjoram', 'cooking'],
  },
  {
    id: 'lemongrass',
    category: 'herbs',
    nameAr: 'عشب الليمون',
    nameEn: 'Lemongrass',
    descAr: 'عشب الليمون المصري بنكهة منعشة',
    descEn: 'Egyptian lemongrass with refreshing flavor',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['herbs', 'lemongrass', 'herbal-tea'],
  },
  // Seeds
  {
    id: 'fennel-seeds',
    category: 'seeds',
    nameAr: 'بذور الشمر',
    nameEn: 'Fennel Seeds',
    descAr: 'بذور شمر مصرية بجودة ممتازة',
    descEn: 'Premium quality Egyptian fennel seeds',
    image: 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['seeds', 'fennel', 'spice'],
  },
  {
    id: 'coriander-seeds',
    category: 'seeds',
    nameAr: 'بذور الكزبرة',
    nameEn: 'Coriander Seeds',
    descAr: 'كزبرة مصرية بحجم منتظم وجودة عالية',
    descEn: 'Egyptian coriander with uniform size and high quality',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['seeds', 'coriander', 'spice'],
  },
  {
    id: 'flaxseeds',
    category: 'seeds',
    nameAr: 'بذور الكتان',
    nameEn: 'Flaxseeds',
    descAr: 'بذور كتان مصرية بجودة تصديرية',
    descEn: 'Export-grade Egyptian flaxseeds',
    image: 'https://images.unsplash.com/photo-1611516491426-03025e6043c8?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['seeds', 'flax', 'health'],
  },
  {
    id: 'sesame',
    category: 'seeds',
    nameAr: 'السمسم',
    nameEn: 'Sesame Seeds',
    descAr: 'سمسم مصري أبيض ومحمص عالي الجودة',
    descEn: 'High-quality Egyptian white and roasted sesame',
    image: 'https://images.unsplash.com/photo-1612540195400-db2fde4f3bbb?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['seeds', 'sesame', 'cooking'],
  },
  // Spices
  {
    id: 'cumin',
    category: 'spices',
    nameAr: 'الكمون',
    nameEn: 'Cumin',
    descAr: 'كمون مصري بلون ورائحة استثنائية',
    descEn: 'Egyptian cumin with exceptional color and aroma',
    image: 'https://images.unsplash.com/photo-1599909356648-43e2f6ae4b2b?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['spices', 'cumin', 'cooking'],
  },
  {
    id: 'turmeric',
    category: 'spices',
    nameAr: 'الكركم',
    nameEn: 'Turmeric',
    descAr: 'كركم مصري بنسبة كركمين عالية',
    descEn: 'Egyptian turmeric with high curcumin content',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['spices', 'turmeric', 'health'],
  },
  {
    id: 'paprika',
    category: 'spices',
    nameAr: 'الفلفل الأحمر',
    nameEn: 'Paprika',
    descAr: 'فلفل أحمر مصري بلون زاهٍ ونكهة قوية',
    descEn: 'Egyptian paprika with vibrant color and bold flavor',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['spices', 'paprika', 'cooking'],
  },
  {
    id: 'cinnamon',
    category: 'spices',
    nameAr: 'القرفة',
    nameEn: 'Cinnamon',
    descAr: 'قرفة مصرية بجودة وعطر مميزين',
    descEn: 'Egyptian cinnamon of distinctive quality and fragrance',
    image: 'https://images.unsplash.com/photo-1557908526-10bce8aa92b3?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['spices', 'cinnamon', 'baking'],
  },
  // Dehydrated Vegetables
  {
    id: 'dried-onion',
    category: 'dehydrated',
    nameAr: 'البصل المجفف',
    nameEn: 'Dried Onion',
    descAr: 'بصل مصري مجفف وعالي الجودة',
    descEn: 'High-quality dried Egyptian onion',
    image: 'https://images.unsplash.com/photo-1618512496248-a07e43164f87?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['dehydrated', 'onion', 'vegetable'],
  },
  {
    id: 'dried-garlic',
    category: 'dehydrated',
    nameAr: 'الثوم المجفف',
    nameEn: 'Dried Garlic',
    descAr: 'ثوم مصري مجفف بنكهة قوية وجودة صناعية',
    descEn: 'Dried Egyptian garlic with bold flavor and industrial quality',
    image: 'https://images.unsplash.com/photo-1587049332298-1c42e83937a7?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['dehydrated', 'garlic', 'vegetable'],
  },
  {
    id: 'dried-tomato',
    category: 'dehydrated',
    nameAr: 'الطماطم المجففة',
    nameEn: 'Dried Tomatoes',
    descAr: 'طماطم مصرية مجففة بجودة تصديرية',
    descEn: 'Export-grade dried Egyptian tomatoes',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['dehydrated', 'tomato', 'vegetable'],
  },
  {
    id: 'dried-pepper',
    category: 'dehydrated',
    nameAr: 'الفلفل المجفف',
    nameEn: 'Dried Bell Pepper',
    descAr: 'فلفل مجفف بألوان وأصناف متعددة',
    descEn: 'Dried bell pepper in various colors and varieties',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80&auto=format&fit=crop',
    origin: 'Egypt',
    tags: ['dehydrated', 'pepper', 'vegetable'],
  },
];

export const testimonials = [
  {
    id: 1,
    nameAr: 'أحمد الكريم',
    nameEn: 'Ahmed Al Kareem',
    roleAr: 'مدير مشتريات - شركة أوروبية',
    roleEn: 'Procurement Manager - European Company',
    textAr: 'الرحيق هربس شريك موثوق. جودة المنتجات ثابتة واحترافية التعامل مميزة في كل مرحلة من مراحل التصدير.',
    textEn: 'Alraheeq Herbs is a trusted partner. Product quality is consistent and their professionalism stands out at every stage of export.',
    country: '🇩🇪',
    rating: 5,
  },
  {
    id: 2,
    nameAr: 'ماريا سانتوس',
    nameEn: 'Maria Santos',
    roleAr: 'مستوردة - أمريكا اللاتينية',
    roleEn: 'Importer - Latin America',
    textAr: 'منتجات ممتازة من أعشاب مصرية طبيعية. فريق احترافي يهتم بتفاصيل التوثيق والشحن.',
    textEn: 'Excellent products from natural Egyptian herbs. A professional team that cares about documentation and shipping details.',
    country: '🇧🇷',
    rating: 5,
  },
  {
    id: 3,
    nameAr: 'يانج وي',
    nameEn: 'Yang Wei',
    roleAr: 'مدير تصدير - آسيا',
    roleEn: 'Export Director - Asia',
    textAr: 'تعاملنا مع الرحيق هربس لطلبيات الكمون والكركم. الجودة عالية والتسليم في الموعد.',
    textEn: 'We worked with Alraheeq Herbs for cumin and turmeric orders. High quality and on-time delivery.',
    country: '🇨🇳',
    rating: 5,
  },
];
